### PR TITLE
Fix the heading in the CODE_OF_CONDUCT.md file.

### PR DESCRIPTION
**Pull request by Leiloukou**
# The reason for this contribution

The first line of your code of conduct has a typo/error, regarding the space between the hashtag and the heading text.
I suggest that you add a space after the hashtag at the first line because it won't render correctly if you don't have a space as a separator between the hashtag and text.

# The comparison

## Before
Here is the rendered blob before:
(note the first line does not show up as a regular heading.)

before-shopfy

## After

The first line is displayed correctly now.
This is what it would look like if you decided to accept my contribution:

Screenshot 2022-02-22 12 53 46 PM

This is my first open-source contribution, so if I did anything wrong, please inform me so that I could do better next time.

### CODE REVIEW

**Comment by Leiloukou** [comment]
I hope this is good enough, please, if you have anything else you would like me to help with,
I am fine with almost anything.

**Comment by Leiloukou** [comment]
Here is the .patch file.

https://patch-diff.githubusercontent.com/raw/spiral/shopify-starter-kit/pull/53.patch

**Comment by Leiloukou** [comment]
I do also suggest using the contributor covenant v2.1,
because it is a lot better.

Here is the Html version:
https://www.contributor-covenant.org/version/2/1/code_of_conduct/

Here is the markdown version:
https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md

**Comment by Kreezag** [comment]
Thanks a lot for your suggestion!

**Comment by Leiloukou** [comment]
My first PR worked!
Thank you so much for accepting!

**Pull request merged**
